version: '3.1'

services:
  apiserver:
    image: abb0s0088/mra-assets-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5200:5201"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"