version: '3.4'

services:
  api:
    image: abb0s0088/mra-assets-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cert1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"