version: '3.4'

services:
  api:
    image: abb0s0088/mra-assets-server:latest
    container_name: assets-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:443
      - ASPNETCORE_HTTP_PORT=8002
    volumes:
      - ${HOME}/.aspnet/https:/https/
    ports:
      - "8002:443"
    depends_on:
      - mongodb
      - mongo-express
      - seq
  
  mongodb:
    image: mongo:latest
    container_name: assets-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    image: mongo-express
    container_name: assets-db-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: MongoSrp
      ME_CONFIG_BASICAUTH_PASSWORD: Mongo1234$
  
  seq:
    image: datalust/seq:latest
    container_name: assets-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8000:80"